// <auto-generated />
using System;
using LupexWallet.Wallets.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.Wallets.Infrastructure.Migrations
{
    [DbContext(typeof(WalletsDbContext))]
    partial class WalletsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallets")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.Wallets.Domain.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AccountingStartDate")
                        .HasColumnType("date")
                        .HasColumnName("accounting_start_date");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("icon");

                    b.Property<bool>("IncludeInTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_total");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PurposeDescription")
                        .HasColumnType("text")
                        .HasColumnName("purpose_description");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_type_id");

                    b.Property<decimal>("_currentBalanceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("current_balance_amount");

                    b.Property<decimal>("_initialBalanceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_balance_amount");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_wallets_currency");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_wallets_display_order")
                        .HasFilter("NOT is_archived");

                    b.HasIndex("IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_wallets_single_primary")
                        .HasFilter("is_primary");

                    b.HasIndex("WalletTypeId")
                        .HasDatabaseName("ix_wallets_wallet_type");

                    b.ToTable("wallets", "wallets", t =>
                        {
                            t.HasCheckConstraint("ck_wallets_primary_included_in_total", "NOT is_primary OR include_in_total");

                            t.HasCheckConstraint("ck_wallets_primary_not_archived", "NOT (is_primary AND is_archived)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
