// <auto-generated />
using System;
using LupexWallet.BalanceHistory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.BalanceHistory.Infrastructure.Migrations
{
    [DbContext(typeof(BalanceHistoryDbContext))]
    partial class BalanceHistoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("balance_history")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.BalanceHistory.Domain.BalanceSnapshot", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("_balanceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("balance_amount");

                    b.HasKey("WalletId", "SnapshotDate")
                        .HasName("pk_balance_snapshots");

                    b.HasIndex("WalletId", "SnapshotDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_balance_snapshots_wallet_date_desc");

                    b.ToTable("balance_snapshots", "balance_history");
                });
#pragma warning restore 612, 618
        }
    }
}
