// <auto-generated />
using System;
using LupexWallet.Audit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.Audit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.Audit.Domain.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_entries_entity");

                    b.ToTable("audit_entries", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_entries_actor_kind", "actor_kind IN ('User', 'System')");
                        });
                });

            modelBuilder.Entity("LupexWallet.Audit.Domain.AuditEntry", b =>
                {
                    b.OwnsOne("LupexWallet.Audit.Domain.AuditActor", "Actor", b1 =>
                        {
                            b1.Property<Guid>("AuditEntryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("actor_kind");

                            b1.Property<string>("SystemProcessName")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("actor_system_process");

                            b1.HasKey("AuditEntryId");

                            b1.ToTable("audit_entries", "audit");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId")
                                .HasConstraintName("fk_audit_entries_audit_entries_id");
                        });

                    b.Navigation("Actor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
