// <auto-generated />
using System;
using LupexWallet.Operations.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.Operations.Infrastructure.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260903195918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("operations")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.Operations.Domain.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentMode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("adjustment_mode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date")
                        .HasColumnName("operation_date");

                    b.Property<Guid>("OperationTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_type_id");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<decimal>("_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<decimal>("_appliedDeltaAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("applied_delta_amount");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("OperationTypeId")
                        .HasDatabaseName("ix_operations_operation_type");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("ix_operations_transfer")
                        .HasFilter("transfer_id IS NOT NULL");

                    b.HasIndex("WalletId", "OperationDate")
                        .HasDatabaseName("ix_operations_wallet_date");

                    b.ToTable("operations", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_operations_adjustment_mode", "adjustment_mode IN ('Absolute', 'Delta') OR adjustment_mode IS NULL");
                        });
                });

            modelBuilder.Entity("LupexWallet.Operations.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_id");

                    b.Property<Guid>("SourceOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_operation_id");

                    b.Property<Guid>("SourceWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_wallet_id");

                    b.Property<Guid>("TargetOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_operation_id");

                    b.Property<Guid>("TargetWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_wallet_id");

                    b.Property<DateOnly>("TransferDate")
                        .HasColumnType("date")
                        .HasColumnName("transfer_date");

                    b.Property<decimal>("_amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("SourceWalletId")
                        .HasDatabaseName("ix_transfers_source_wallet");

                    b.HasIndex("TargetWalletId")
                        .HasDatabaseName("ix_transfers_target_wallet");

                    b.ToTable("transfers", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_transfers_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transfers_distinct_wallets", "source_wallet_id <> target_wallet_id");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
