<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\SharedKernel\LupexWallet.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Wallets\Wallets.Application\LupexWallet.Wallets.Application.csproj" />
    <ProjectReference Include="..\..\BalanceHistory\BalanceHistory.Application\LupexWallet.BalanceHistory.Application.csproj" />
    <ProjectReference Include="..\..\ExchangeRates\ExchangeRates.Application\LupexWallet.ExchangeRates.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
