// <auto-generated />
using System;
using LupexWallet.ExchangeRates.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.ExchangeRates.Infrastructure.Migrations
{
    [DbContext(typeof(ExchangeRatesDbContext))]
    [Migration("20260911093033_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exchange_rates")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.ExchangeRates.Domain.ExchangeRateQuote", b =>
                {
                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("_rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.HasKey("FromCurrencyId", "ToCurrencyId")
                        .HasName("pk_latest_exchange_rates");

                    b.ToTable("latest_exchange_rates", "exchange_rates", t =>
                        {
                            t.HasCheckConstraint("ck_latest_rates_distinct_currencies", "from_currency_id <> to_currency_id");

                            t.HasCheckConstraint("ck_latest_rates_positive", "rate > 0");
                        });
                });

            modelBuilder.Entity("LupexWallet.ExchangeRates.Domain.HistoricalExchangeRate", b =>
                {
                    b.Property<Guid>("FromCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_currency_id");

                    b.Property<Guid>("ToCurrencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_currency_id");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rate_date");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<decimal>("_rate")
                        .HasColumnType("numeric")
                        .HasColumnName("rate");

                    b.HasKey("FromCurrencyId", "ToCurrencyId", "RateDate")
                        .HasName("pk_historical_exchange_rates");

                    b.ToTable("historical_exchange_rates", "exchange_rates", t =>
                        {
                            t.HasCheckConstraint("ck_historical_rates_distinct_currencies", "from_currency_id <> to_currency_id");

                            t.HasCheckConstraint("ck_historical_rates_positive", "rate > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
