/** One ISO 4217 currency: its 3-letter code and a Russian display name. */
export interface IsoCurrency {
  code: string;
  name: string;
}

const RAW_ISO_CURRENCIES: readonly IsoCurrency[] = [
  { code: 'RUB', name: 'Российский рубль' },
  { code: 'USD', name: 'Доллар США' },
  { code: 'EUR', name: 'Евро' },
  { code: 'GBP', name: 'Фунт стерлингов' },
  { code: 'JPY', name: 'Японская иена' },
  { code: 'CNY', name: 'Китайский юань' },
  { code: 'CHF', name: 'Швейцарский франк' },
  { code: 'KZT', name: 'Казахстанский тенге' },
  { code: 'BYN', name: 'Белорусский рубль' },
  { code: 'UAH', name: 'Украинская гривна' },
  { code: 'AMD', name: 'Армянский драм' },
  { code: 'AZN', name: 'Азербайджанский манат' },
  { code: 'GEL', name: 'Грузинский лари' },
  { code: 'KGS', name: 'Киргизский сом' },
  { code: 'TJS', name: 'Таджикский сомони' },
  { code: 'TMT', name: 'Туркменский манат' },
  { code: 'UZS', name: 'Узбекский сум' },
  { code: 'MDL', name: 'Молдавский лей' },
  { code: 'AUD', name: 'Австралийский доллар' },
  { code: 'CAD', name: 'Канадский доллар' },
  { code: 'NZD', name: 'Новозеландский доллар' },
  { code: 'HKD', name: 'Гонконгский доллар' },
  { code: 'SGD', name: 'Сингапурский доллар' },
  { code: 'INR', name: 'Индийская рупия' },
  { code: 'PKR', name: 'Пакистанская рупия' },
  { code: 'BDT', name: 'Бангладешская така' },
  { code: 'LKR', name: 'Шри-ланкийская рупия' },
  { code: 'NPR', name: 'Непальская рупия' },
  { code: 'KRW', name: 'Южнокорейская вона' },
  { code: 'TWD', name: 'Новый тайваньский доллар' },
  { code: 'THB', name: 'Тайский бат' },
  { code: 'VND', name: 'Вьетнамский донг' },
  { code: 'IDR', name: 'Индонезийская рупия' },
  { code: 'MYR', name: 'Малайзийский ринггит' },
  { code: 'PHP', name: 'Филиппинское песо' },
  { code: 'MMK', name: 'Мьянманский кьят' },
  { code: 'KHR', name: 'Камбоджийский риель' },
  { code: 'LAK', name: 'Лаосский кип' },
  { code: 'MNT', name: 'Монгольский тугрик' },
  { code: 'TRY', name: 'Турецкая лира' },
  { code: 'ILS', name: 'Израильский новый шекель' },
  { code: 'AED', name: 'Дирхам ОАЭ' },
  { code: 'SAR', name: 'Саудовский риял' },
  { code: 'QAR', name: 'Катарский риал' },
  { code: 'KWD', name: 'Кувейтский динар' },
  { code: 'BHD', name: 'Бахрейнский динар' },
  { code: 'OMR', name: 'Оманский риал' },
  { code: 'JOD', name: 'Иорданский динар' },
  { code: 'LBP', name: 'Ливанский фунт' },
  { code: 'IQD', name: 'Иракский динар' },
  { code: 'IRR', name: 'Иранский риал' },
  { code: 'AFN', name: 'Афганский афгани' },
  { code: 'EGP', name: 'Египетский фунт' },
  { code: 'ZAR', name: 'Южноафриканский рэнд' },
  { code: 'NGN', name: 'Нигерийская найра' },
  { code: 'KES', name: 'Кенийский шиллинг' },
  { code: 'GHS', name: 'Ганский седи' },
  { code: 'MAD', name: 'Марокканский дирхам' },
  { code: 'DZD', name: 'Алжирский динар' },
  { code: 'TND', name: 'Тунисский динар' },
  { code: 'ETB', name: 'Эфиопский быр' },
  { code: 'UGX', name: 'Угандийский шиллинг' },
  { code: 'TZS', name: 'Танзанийский шиллинг' },
  { code: 'XOF', name: 'Франк КФА BCEAO' },
  { code: 'XAF', name: 'Франк КФА BEAC' },
  { code: 'BRL', name: 'Бразильский реал' },
  { code: 'MXN', name: 'Мексиканское песо' },
  { code: 'ARS', name: 'Аргентинское песо' },
  { code: 'CLP', name: 'Чилийское песо' },
  { code: 'COP', name: 'Колумбийское песо' },
  { code: 'PEN', name: 'Перуанский соль' },
  { code: 'UYU', name: 'Уругвайское песо' },
  { code: 'BOB', name: 'Боливиано' },
  { code: 'PYG', name: 'Парагвайский гуарани' },
  { code: 'VES', name: 'Боливар' },
  { code: 'CRC', name: 'Костариканский колон' },
  { code: 'GTQ', name: 'Гватемальский кетсаль' },
  { code: 'DOP', name: 'Доминиканское песо' },
  { code: 'JMD', name: 'Ямайский доллар' },
  { code: 'TTD', name: 'Доллар Тринидада и Тобаго' },
  { code: 'CUP', name: 'Кубинское песо' },
  { code: 'PAB', name: 'Панамский бальбоа' },
  { code: 'HNL', name: 'Гондурасская лемпира' },
  { code: 'NIO', name: 'Никарагуанская кордоба' },
  { code: 'SVC', name: 'Сальвадорский колон' },
  { code: 'BZD', name: 'Белизский доллар' },
  { code: 'HTG', name: 'Гаитянский гурд' },
  { code: 'PLN', name: 'Польский злотый' },
  { code: 'CZK', name: 'Чешская крона' },
  { code: 'HUF', name: 'Венгерский форинт' },
  { code: 'RON', name: 'Румынский лей' },
  { code: 'BGN', name: 'Болгарский лев' },
  { code: 'HRK', name: 'Хорватская куна' },
  { code: 'RSD', name: 'Сербский динар' },
  { code: 'ALL', name: 'Албанский лек' },
  { code: 'MKD', name: 'Македонский денар' },
  { code: 'BAM', name: 'Конвертируемая марка' },
  { code: 'ISK', name: 'Исландская крона' },
  { code: 'NOK', name: 'Норвежская крона' },
  { code: 'SEK', name: 'Шведская крона' },
  { code: 'DKK', name: 'Датская крона' },
  { code: 'XCD', name: 'Восточно-карибский доллар' },
  { code: 'BBD', name: 'Барбадосский доллар' },
  { code: 'BSD', name: 'Багамский доллар' },
  { code: 'BMD', name: 'Бермудский доллар' },
  { code: 'KYD', name: 'Доллар Островов Кайман' },
  { code: 'FJD', name: 'Доллар Фиджи' },
  { code: 'PGK', name: 'Кина Папуа-Новой Гвинеи' },
  { code: 'WST', name: 'Самоанская тала' },
  { code: 'TOP', name: 'Тонганская паанга' },
  { code: 'SBD', name: 'Доллар Соломоновых Островов' },
  { code: 'VUV', name: 'Вануатский вату' },
  { code: 'XPF', name: 'Тихоокеанский франк' },
  { code: 'ANG', name: 'Нидерландский антильский гульден' },
  { code: 'AWG', name: 'Арубанский флорин' },
  { code: 'SRD', name: 'Суринамский доллар' },
  { code: 'GYD', name: 'Гайанский доллар' },
  { code: 'ZMW', name: 'Замбийская квача' },
  { code: 'MWK', name: 'Малавийская квача' },
  { code: 'MZN', name: 'Мозамбикский метикал' },
  { code: 'AOA', name: 'Ангольская кванза' },
  { code: 'NAD', name: 'Намибийский доллар' },
  { code: 'BWP', name: 'Ботсванская пула' },
  { code: 'SZL', name: 'Свазилендский лилангени' },
  { code: 'LSL', name: 'Лесотское лоти' },
  { code: 'MUR', name: 'Маврикийская рупия' },
  { code: 'SCR', name: 'Сейшельская рупия' },
  { code: 'MGA', name: 'Малагасийский ариари' },
  { code: 'RWF', name: 'Руандийский франк' },
  { code: 'BIF', name: 'Бурундийский франк' },
  { code: 'CDF', name: 'Конголезский франк' },
  { code: 'DJF', name: 'Джибутийский франк' },
  { code: 'SOS', name: 'Сомалийский шиллинг' },
  { code: 'SDG', name: 'Суданский фунт' },
  { code: 'SSP', name: 'Южносуданский фунт' },
  { code: 'LYD', name: 'Ливийский динар' },
  { code: 'SYP', name: 'Сирийский фунт' },
  { code: 'YER', name: 'Йеменский риал' },
  { code: 'BND', name: 'Брунейский доллар' },
  { code: 'BTN', name: 'Бутанский нгултрум' },
  { code: 'MVR', name: 'Мальдивская руфия' },
  { code: 'PLZ', name: 'Замбийский пула' },
  { code: 'KPW', name: 'Северокорейская вона' },
  { code: 'MOP', name: 'Патака Макао' },
  { code: 'CVE', name: 'Эскудо Кабо-Верде' },
  { code: 'GMD', name: 'Гамбийский даласи' },
  { code: 'GNF', name: 'Гвинейский франк' },
  { code: 'LRD', name: 'Либерийский доллар' },
  { code: 'SLE', name: 'Сьерра-леонский леоне' },
  { code: 'STN', name: 'Добра Сан-Томе и Принсипи' },
  { code: 'ERN', name: 'Эритрейская накфа' },
  { code: 'KMF', name: 'Коморский франк' },
  { code: 'FKP', name: 'Фунт Фолклендских островов' },
  { code: 'GIP', name: 'Гибралтарский фунт' },
  { code: 'SHP', name: 'Фунт Святой Елены' },
  { code: 'IMP', name: 'Фунт острова Мэн' },
  { code: 'JEP', name: 'Джерсийский фунт' },
  { code: 'GGP', name: 'Гернсийский фунт' },
];

/**
 * Currently circulating ISO 4217 currencies, sorted by code, for the "add new
 * currency" pickers (features/wallets, features/reference-data) — lets the
 * user pick a currency instead of typing its code/name by hand, where a typo
 * would silently create a bogus currency (ReferenceData has no external
 * validation for these fields).
 */
export const ISO_CURRENCIES: readonly IsoCurrency[] = [...RAW_ISO_CURRENCIES].sort((a, b) =>
  a.code.localeCompare(b.code),
);
