// <auto-generated />
using System;
using LupexWallet.ReferenceData.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LupexWallet.ReferenceData.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDataDbContext))]
    [Migration("20260903192230_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reference_data")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LupexWallet.ReferenceData.Domain.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_currencies_code");

                    b.ToTable("currencies", "reference_data");
                });

            modelBuilder.Entity("LupexWallet.ReferenceData.Domain.OperationBehaviorKind", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_operation_behavior_kinds");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_operation_behavior_kinds_code");

                    b.ToTable("operation_behavior_kinds", "reference_data");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24064f7c-82b3-4407-a1bb-b3706c0643c1"),
                            Code = "Income",
                            Name = "Доход"
                        },
                        new
                        {
                            Id = new Guid("d042ac13-0644-4ded-8fdd-518e6035b107"),
                            Code = "Expense",
                            Name = "Расход"
                        },
                        new
                        {
                            Id = new Guid("107ca9ff-3b38-4a58-85d7-236703f49a46"),
                            Code = "Transfer",
                            Name = "Перевод"
                        },
                        new
                        {
                            Id = new Guid("322fb879-0c8e-464e-bca1-9e84964ad232"),
                            Code = "Adjustment",
                            Name = "Ручная корректировка"
                        });
                });

            modelBuilder.Entity("LupexWallet.ReferenceData.Domain.OperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BehaviorKindId")
                        .HasColumnType("uuid")
                        .HasColumnName("behavior_kind_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operation_types");

                    b.HasIndex("BehaviorKindId")
                        .HasDatabaseName("ix_operation_types_behavior_kind");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_operation_types_active_name")
                        .HasFilter("is_active");

                    b.ToTable("operation_types", "reference_data");
                });

            modelBuilder.Entity("LupexWallet.ReferenceData.Domain.WalletType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wallet_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_wallet_types_active_name")
                        .HasFilter("is_active");

                    b.ToTable("wallet_types", "reference_data");
                });

            modelBuilder.Entity("LupexWallet.ReferenceData.Domain.OperationType", b =>
                {
                    b.HasOne("LupexWallet.ReferenceData.Domain.OperationBehaviorKind", null)
                        .WithMany()
                        .HasForeignKey("BehaviorKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operation_types_operation_behavior_kinds_behavior_kind_id");
                });
#pragma warning restore 612, 618
        }
    }
}
